# Site settings
title: What's New | Easy Insight
email: sales@easy-insight.com
description: > # this means to ignore newlines until "baseurl:"
  Read about new features or changes to Easy Insight.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.easy-insight.com" # the base hostname & protocol for your site
twitter_username: easyinsight
excerpt_separator: <!--more-->
# Build settings
markdown: kramdown
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"