# Site settings
title: Easy Insight
email: jboe@easy-insight.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.easy-insight.com" # the base hostname & protocol for your site
twitter_username: easyinsight
excerpt_separator: <!--more-->
# Build settings
markdown: kramdown
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"